Fullstack with python and js/ProjectClass11/AEROLINEA/urls.py
from django import views
from django.urls import path, include
from . import views

app_name = "AEROLINEA"
urlpatterns = [
    path('', views.index, name="index"),
    path('int:<vuelo_id>', views.vuelo, name="vuelo"),
    path('int:<vuelo_id>/reserva', views.reserva, name="reserva"),
]

Fullstack with python and js/ProjectClass11/ANIONUEVO/urls.py
from django import views
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
]

Fullstack with python and js/ProjectClass11/ProjectClass11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ANIONUEVO/', include("ANIONUEVO.urls")),
    path('TAREAS/', include("TAREAS.urls")),
    path('AEROLINEA/', include("AEROLINEA.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('registrarse/', include("USUARIOS.urls")),
]

Fullstack with python and js/ProjectClass11/TAREAS/urls.py
from django import views
from django.urls import path, include
from . import views

app_name = "TAREAS"
urlpatterns = [
    path('', views.index, name="index"),
    path('agregar', views.agregar, name="agregar"),
]

Fullstack with python and js/ProjectClass11/USUARIOS/urls.py
from django.urls import path, include
from . import views

app_name = "USUARIOS"
urlpatterns = [
    path('', views.registrarse, name="registrarse"),
]

Fullstack with python and js/ProjectClass11/AEROLINEA/models.py
from re import M
from django.db import models

# Create your models here.

class Aeropuerto(models.Model):
    codigo = models.CharField(max_length=3)
    ciudad = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.ciudad} ({self.codigo})"


class Vuelo(models.Model):
    origen = models.ForeignKey(Aeropuerto, on_delete=models.CASCADE, related_name="salidas")
    destino = models.ForeignKey(Aeropuerto, on_delete=models.CASCADE, related_name="arribos")
    duracion = models.IntegerField()

    def __str__(self):
        return f"Vuelo #{self.id}: {self.origen} hacia {self.destino}"

class Pasajero(models.Model):
    nombre = models.CharField(max_length=64)
    apellido = models.CharField(max_length=64)
    vuelos = models.ManyToManyField(Vuelo, blank=True, related_name="pasajeros")

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

# un_vuelo = Vuelo("Posadas","Buenos Aires", 2)
# un_vuelo.save()
# Vuelo.objects.all()

Fullstack with python and js/ProjectClass11/USUARIOS/models.py
from django.db import models

# Create your models here.

Fullstack with python and js/ProjectClass11/USUARIOS/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistroForm(UserCreationForm):
    username = forms.CharField(
        label='Usuario', widget=forms.TextInput(attrs={'class': 'usuario'}), max_length=150, required=True, help_text='Requerido. 150 caracteres o menos. Letras, dígitos y @ /. / + / - / _ solamente.')
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='Requerido. Al menos 8 caracteres y no pueden ser todos numeros.')
    password2 = forms.CharField(
        label='Repetir Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='Requerido. Ingrese la misma contraseña que antes, para verificación.')
    first_name = forms.CharField(
        label='Nombre', widget=forms.TextInput(attrs={'class': 'nombre'}), max_length=30, required=False, help_text='Opcional.')
    last_name = forms.CharField(
        label='Apellido', widget=forms.TextInput(attrs={'class': 'apellido'}), max_length=30, required=False, help_text='Opcional.')
    email = forms.EmailField(
        label='Email', widget=forms.TextInput(attrs={'class': 'email'}), max_length=254, required=True, help_text='Se requiere una direccion de email valida.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

Fullstack with python and js/ProjectClass11/AEROLINEA/views.py
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render
from idna import valid_contextj
from .models import Pasajero, Vuelo
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    pass

def index(request):
    return render(request, "vuelos/index.html", {
        "lista_vuelos": Vuelo.objects.all()
    })

def vuelo(request, vuelo_id):
    vuelo = Vuelo.objects.get(id = vuelo_id)
    pasajeros = vuelo.pasajeros.all()
    no_son_pasajeros = Pasajero.objects.exclude(vuelos=vuelo).all()
    return render(request, "vuelos/vuelo.html", {
        "vuelo": vuelo,
        "pasajeros": pasajeros,
        "no_son_pasajeros": no_son_pasajeros
    })

def reserva(request, vuelo_id):
    if request.method == "POST":
        vuelo = Vuelo.objects.get(pk=vuelo_id)
        pasajero_id = int(request.POST["pasajero"])
        pasajero = Pasajero.objects.get(pk=pasajero_id)
        pasajero.vuelos.add(vuelo)
        return HttpResponseRedirect(reverse("AEROLINEA:vuelo", args=(vuelo.id)))

Fullstack with python and js/ProjectClass11/ANIONUEVO/views.py
from django.shortcuts import render
import datetime

# Create your views here.

def index(request):
    ahora = datetime.datetime.now()
    return render(request, "anionuevo/index.html", {
        "anionuevo": ahora.month == 1 and ahora.day == 1 or ahora.month == 12 and ahora.day == 31
    })

Fullstack with python and js/ProjectClass11/TAREAS/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse

# Create your views here.

# tareas = ["baniarse", "veestirse", "prepararse", "salir"]
# Sesiones

class FormAltaTarea(forms.Form):
    tarea = forms.CharField(label = "Nueva Tarea")

def index(request):
    if "tareas" not in request.session:
        request.session["tareas"] = []
    return render(request, "tareas/index.html", {
        "tareas": request.session["tareas"]
    })

    # return render(request, "tareas/index.html", {
    #     "tareas": tareas
    # })

def agregar(request):

    if request.method == "POST":
        form = FormAltaTarea(request.POST)
        if form.is_valid():
            tarea = form.cleaned_data["tarea"]
            request.session["tareas"] += [tarea]
            return HttpResponseRedirect(reverse("TAREAS:index"))
        else:
            return render(request, "tareas/agregar.html", {
                "formulario_alta_tarea": form
            })
    else:
        return render(request, "tareas/agregar.html", {
            "fromulario_alta_tarea": FormAltaTarea()
    })

Fullstack with python and js/ProjectClass11/USUARIOS/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import *

def registrarse(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()          
            return HttpResponseRedirect(reverse('login'))
    else:
        form = RegistroForm()
    return render(request, 'registration/registro.html', {
        'form': form
        })

Fullstack with python and js/ProjectClass11/AEROLINEA/templates/vuelos/index.html
{% extends "vuelos/layout.html" %}
<!--De layout-->
<!-- Body -->
{% block body %}

<h1>Vuelos</h1>
<ul>
    {% for un_vuelo in lista_vuelos %}
    <li>
        <a href="{% url 'AEROLINEA:vuelo' un_vuelo.id %}"> #{{un_vuelo.id}}</a> {{un_vuelo.origen}} hacia {{un_vuelo.destino}}
    </li>
    <!-- Termina el for -->
    {% endfor %}
</ul>

<!-- Termina el body -->
{% endblock %}

Fullstack with python and js/ProjectClass11/AEROLINEA/templates/vuelos/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vuelos</title>
    {% block head %} {% endblock %}
</head>

<body>
    {% block body %} {% endblock %}
</body>

</html>

Fullstack with python and js/ProjectClass11/AEROLINEA/templates/vuelos/vuelo.html
{% extends "vuelos/layout.html" %}
<!--De layout-->
<!-- Body -->
{% block body %}

<h2>Vuelo</h2>
<h3>Lista de Pasajeros</h3>
<ul>
    {% for un_pasajero in pasajeros %}
    <li>{{un_pasajero}}</li>
    {% empty %}
    <li>No hay pasajeros registrados.</li>
    <!-- Termina el For -->
    {% endfor %}
</ul>

<h2>Reserva</h2>
<form action="{% url 'AEROLINEA:reserva' vuelo.id %}" method="post">
    {% csrf_token %}
    <select name="pasajero" id="">
    {% for un_pasajero in no_son_pasajeros %}
    <option value="{{un_pasajero.id}}">{{un_pasajero}}</option>
    <!-- End for -->
    {% endfor %}
  </select>
    <input type="submit" value="RESERVAR" />
</form>
<br />
<a href="{% url 'AEROLINEA:index' %}">Volver</a>

<!-- Termina el body -->
{% endblock %}

Fullstack with python and js/ProjectClass11/ANIONUEVO/templates/anionuevo/index.html
{% extends "anionuevo/layout.html" %}
<!--De layout-->
{% block body %}

<!--AQUI ES DONDE PUEDO TRABAJAR CON LOGICA DENTRO DE UN TEMPLATE-->
{% if anionuevo %}
<hl>SI</h1>
    {% else %}
    <h1>NO</h1>
    {% endif %}
    <!-- asd -->
    {% endblock %}

Fullstack with python and js/ProjectClass11/ANIONUEVO/templates/anionuevo/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Es anio nuevo hoy?</title>
</head>

<body>
    {% block body %} {% endblock %}
</body>

</html>

Fullstack with python and js/ProjectClass11/TAREAS/templates/tareas/agregar.html
{% extends "tareas/layout.html" %}
<!--De layout-->
{% block head %}
<title>Agregar</title>
{% endblock %}

<!-- Empieza el bloque body -->
{% block body %}
<!-- El for para las listas -->
{% for una_tarea in tareas %}

<h1>Alta de Tarea</h1>
<form action="{% url 'TAREAS:agregar' %}" method="post">
    {% csrf_token %}
    <!--Saca el error del CSRF token-->

    {{ formulario_alta_tarea }}
    <!-- <input type="text" name="tarea" /> -->
    <input type="submit" value="Guardar" />
</form>

<div class="acciones">
    <a href="{% url 'TAREAS:index' %}"> Volver a la lista de tareas </a>
</div>

{% endfor %}
<!-- Termina el bloque -->
{% endblock %}

Fullstack with python and js/ProjectClass11/TAREAS/templates/tareas/index.html
{% extends "tareas/layout.html" %}
<!--De layout-->
{% block body %} {% for una_tarea in tareas %}

<ul>
    <li>{{ una_tarea }}</li>
</ul>

<div class="acciones">
    <a href="{% url 'TAREAS:agregar' %}"> Agregar una nueva tarea </a>
</div>

{% endfor %} {% endblock %}

Fullstack with python and js/ProjectClass11/TAREAS/templates/tareas/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Es anio nuevo hoy?</title>
    {% block head %} {% endblock %}
</head>

<body>
    {% block body %} {% endblock %}
</body>

</html>